[project]
name = "worklog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.7"
dependencies = [
    "click>=8.1.8",
    "pyyaml>=6.0.2",
    "ruff>=0.9.2",
]
